Fix(BBD-838): Mouse into Sayt, click out, try to search, doesn't work
groupby/storefront-sayt pull request #38
Opened 2017-11-07 14:37 UTC by treeforever

2017-11-10 14:26 UTC, Filip-F requested changes

2017-11-10 14:26 UTC, Filip-F commented on test/unit/autocomplete.ts
> +        .and.calledWith('sayt:activate_next', autocomplete.activateNext)
Use `calledWithExactly` here, as `calledWith` will return true if it was called with these arguments, regardless of if there were any more (eg `flux.off('sayt:activate_next', autocomplete.activateNext, 4)` would pass with `calledWith`), `calledWithExactly` just checks that there are no other arguments.

2017-11-10 18:04 UTC, Vic-Dev submitted a review, later dismissed
Looks good. I agree with fil's comment

2017-11-10 19:55 UTC, Filip-F approved these changes

2017-11-15 21:09 UTC, Vic-Dev approved these changes
Gj. Demo?

2017-11-16 17:23 UTC, merged